numero = int(input('Digite um número: '))
dobro = int(numero * 2)
triplo = int(numero * 3)
raiz = int(numero ** (1/2))
print('O número digitado foi {}, seu dobro é {}, seu triplo é {} e a sua raiz quadrada é {:.2f}!'.format(numero, dobro, triplo, raiz))
