num = int(input('Digite um número: '))
mult0 = int(num * 0)
mult1 = int(num * 1)
mult2 = int(num * 2)
mult3 = int(num * 3)
mult4 = int(num * 4)
mult5 = int(num * 5)
mult6 = int(num * 6)
mult7 = int(num * 7)
mult8 = int(num * 8)
mult9 = int(num * 9)
mult10 = int(num * 10)
print('O valor digitado foi {}, e abaixo segue sua tabuada: \n'.format(num))
print('{} x 0 = {} '.format(num, mult0))
print('{} x 1 = {} '.format(num, mult1))
print('{} x 2 = {} '.format(num, mult2))
print('{} x 3 = {} '.format(num, mult3))
print('{} x 4 = {} '.format(num, mult4))
print('{} x 5 = {} '.format(num, mult5))
print('{} x 6 = {} '.format(num, mult6))
print('{} x 7 = {} '.format(num, mult7))
print('{} x 8 = {} '.format(num, mult8))
print('{} x 9 = {} '.format(num, mult9))
print('{} x 10 = {} '.format(num, mult10))

